audio:
  n_fft: 1200
  num_freq: 601 # n_fft//2 + 1 (LEGACY for 2019 compatibility)
  sample_rate: 16000
  hop_length: 160
  win_length: 400
  min_level_db: -100.0
  ref_level_db: 20.0
  preemphasis: 0.97
  power: 0.30
  
  # VoiceFilter-Lite 2020 NEW PARAMETERS
  num_filterbanks: 128  # PAPER SPEC: 128-dimensional LFBE
  frame_stack_size: 3   # Frame stacking for temporal context (common ASR practice)
  use_stacked_features: true  # Enable frame stacking

model:
  # VoiceFilter-Lite 2020 ARCHITECTURE  
  # PAPER SPEC: "3 LSTM layers, each with 512 nodes"
  lstm_layers: 3
  lstm_dim: 512  # Changed from 400 to 512 per paper
  
  # Input dimension calculation:
  # num_filterbanks * frame_stack_size = 128 * 3 = 384
  input_dim: 384  # 128 filterbanks × 3 stacked frames
  
  # Dual output dimensions (VoiceFilter-Lite 2020)
  mask_dim: 128      # Soft mask output (same as num_filterbanks)
  noise_pred_dim: 2  # Noise type prediction (speech vs non-speech)
  
  # Legacy dimensions (kept for 2019 compatibility)
  fc1_dim: 600
  fc2_dim: 601 # num_freq

data:
  train_dir: ''
  test_dir: ''
  audio_len: 3.0

form:
  input: '*-norm.wav'
  dvec: '*-dvec.txt' # will be calculated on-the-fly
  target:
    wav: '*-target.wav'
    mag: '*-target.pt'        # Legacy 2019 format
    features: '*-target-features.pt'  # NEW: VoiceFilter-Lite 2020 features
  mixed:
    wav: '*-mixed.wav'
    mag: '*-mixed.pt'         # Legacy 2019 format  
    features: '*-mixed-features.pt'   # NEW: VoiceFilter-Lite 2020 features
  noise_type: '*-noise-type.pt'  # VoiceFilter-Lite 2020: noise classification labels

train:
  batch_size: 8
  num_workers: 16
  optimizer: 'adam'
  adam: 0.001
  adabound:
    initial: 0.001
    final: 0.05
  summary_interval: 1
  checkpoint_interval: 1000
  
  # VoiceFilter-Lite 2020 LOSS PARAMETERS
  asymmetric_loss_alpha: 2.0  # PAPER: asymmetric L2 loss parameter
  noise_pred_loss_weight: 0.1 # Weight for noise type prediction loss

# VoiceFilter-Lite 2020 ADAPTIVE SUPPRESSION
# GOOGLE SLIDES EXACT SPECIFICATIONS
adaptive_suppression:
  beta: 0.9    # β ∈ [0,1] - moving average coefficient for streaming
  alpha: 1.0   # a > 0 - linear transform slope (Google slides constraint)
  bias: 0.0    # b ≥ 0 - linear transform bias (Google slides constraint)
  
  # Advanced adaptive suppression settings
  min_suppression: 0.1  # Minimum suppression strength
  max_suppression: 0.9  # Maximum suppression strength
  
  # Noise type thresholds (Google slides classification)
  # 0 = clean speech, or containing non-speech noise
  # 1 = overlapped speech
  clean_threshold: 0.5       # Threshold for detecting clean/non-speech
  overlapped_threshold: 0.5  # Threshold for detecting overlapped speech

log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'

embedder: # d-vector embedder. don't fix it!
  num_mels: 40
  n_fft: 512
  emb_dim: 256
  lstm_hidden: 768
  lstm_layers: 3
  window: 80
  stride: 40
